### ISSUE TITLE
Broken dependency to 'for-core'

### ISSUE THREAD

**Issue by anatol** [fog/fog-profitbricks#15]
`~> 0` causes dependency problem when installing the package using gem:

```
ERROR:  Could not find a valid gem 'fog-core' (~> 0) in any repository
ERROR:  Possible alternatives: fog-core
```

Just drop `~> 0` from gemspec, the dependency qualifier is useless.

**Comment by plribeiro3000** [comment]
:+1:

**Comment by edevenport** [comment]
@anatol - Sorry about that. I reverted the gemspec changes (so much for following the suggestions of the build warnings) and released a new version. Can you confirm this corrects the install?

**Comment by anatol** [comment]
Thanks, it works now.
