### ISSUE TITLE
fog-profitbricks-2.0.1 issue

### ISSUE THREAD

**Issue by areznikov-kabam** [fog/fog-profitbricks#24]
irb(main):001:0> require 'fog'
NameError: undefined local variable or method `__dir__' for main:Objectfrom lib/ruby/gems/1.9.1/gems/fog-profitbricks-2.0.1/lib/fog/profitbricks.rb:4:in`<top (required)>'

**Comment by areznikov-kabam** [comment]
ruby 1.9.1 does not have __dir__

**Comment by tvpartytonight** [comment]
Now that his has been addressed in PR #27, can we get a new release of the 2.x gem? Thank you!

**Comment by plribeiro3000** [comment]
@edevenport Can you take a look at this?

I see a vesion `2.0.1` on rubygems but it is not in github so i dunno where was the last release.

**Comment by edevenport** [comment]
@plribeiro3000 @tvpartytonight  - Would it be possible to wait until #32 is reviewed and merged? This should put fog-profitbricks into a good state. Otherwise, we could do a 2.1.0 release before #32 is merged.

**Comment by tvpartytonight** [comment]
@edevenport how long until that PR is merged? We have some ci that has been broken, but we can work around it for the time being.

**Comment by edevenport** [comment]
@tvpartytonight - The PR has been merged and version 3.0.0 based on the ProfitBricks Cloud API v3 has been released.
