### ISSUE TITLE
Test suite failures

### ISSUE THREAD

**Issue by voxik** [fog/fog-profitbricks#25]
Test suite on travis [1] fails with ```7 failed, 101 succeeded in 0.180315641 seconds``` and I observe the same issue on my environment.

[1] https://travis-ci.org/fog/fog-profitbricks/jobs/160080173

**Comment by edevenport** [comment]
@voxik New and updated tests have been merged into master (#26) which should result in those 7 tests in passing now. #26 also includes new model tests and there will be more to come soon.

**Comment by edevenport** [comment]
Below are the latest Ruby 2.1.1 results. We will be addressing tests with older versions of Ruby soon.

[1] https://travis-ci.org/fog/fog-profitbricks/jobs/161445039

**Comment by voxik** [comment]
Cool, thx for such fast turnaround.
